# Generated by Django 3.2.15 on 2022-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fruit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='fruitType',
            field=models.CharField(choices=[('CTR', 'Citrical'), ('BER', 'Berry')], default='BER', max_length=255),
        ),
    ]
